package net.pisecurity.model;

public enum EventType {
	ALARMTRIGGERED_AUTO, ALARMTRIGGERED_MANUAL,

	ACTIVITY,

	SYSTEM_AUTO_ARMED, SYSTEM_AUTO_DISARMED, SYSTEM_MANUAL_ARMED, SYSTEM_MANUAL_DISARMED,

	ALARMRESET, SYSTEM_START, SYSTEM_SHUTDOWN, CONFIG_CHANGED, INTERNET_ONLINE, INTERNET_OFFLINE,
	
	USERS_NOTIFIED_OF_ALARM,

}
