package net.pisecurity.model;

public enum EventType {
	ALARMTRIGGERED_AUTO,
	ALARMTRIGGERED_MANUAL,
	
	ACTIVITY,
	
	SYSTEM_AUTO_ARMED,
	SYSTEM_AUTO_DISARMED,
	SYSTEM_MANUAL_ARMED,
	SYSTEM_MANUAL_DISARMED,
	
	ALARMRESET,
	
}
